### ISSUE TITLE
hi，AssertionError ,i cann't fix it

### ISSUE THREAD

**Issue by jojokic** [hyw-dev/VFSS#1]
(venv) G:\aibuzhen\VFSS-main>python inference_video.py --exp=2 --img=input --model_type [anime/real]
[!!alt_cuda_corr is not compiled!!]
[Using twins as context encoder]
[Using twins as feature encoder]
[Using stack.]
[Using corr_fn default]
Loaded model
  0%|                                                                                                                                                            | 0/2 [00:00<?, ?it/s]T
raceback (most recent call last):
  File "G:\aibuzhen\VFSS-main\inference_video.py", line 208, in <module>
    assert i2 is not None
AssertionError

**Comment by jojokic** [comment]
hi , i konw why ,i only input 2picture ,when i input 4pictures,it works . by the way,i found the output picture is blurry ,my input pictures's size is 1920*1080, i want to have Pictures with original clarity , how to do ?

**Comment by routineLife1** [comment]
Maybe you can contact me through qq 1315176066
